### ISSUE TITLE
Won't download single YouTube videos or playlists

### ISSUE THREAD

**Issue by sparky000777** [bernardodsanderson/vido#44]
Doesn't work

**Comment by bernardodsanderson** [comment]
Hi @sparky000777, I believe the issue is that the version ElementaryOS/Ubuntu have of youtube-dl is old. You can update with the following intructions: http://ytdl-org.github.io/youtube-dl/download.html

Basically, on the terminal run the following:
`sudo curl -L https://yt-dl.org/downloads/latest/youtube-dl -o /usr/local/bin/youtube-dl`
`sudo chmod a+rx /usr/local/bin/youtube-dl`
